name: checkbox-opencl-regression
summary: Checkbox tests for the kivu classic project
description: |
  Collection of tests to be run on devices that are part of the opencl-regression project
version: '2.0'
confinement: classic
grade: stable

base: core22

# Here are the available applications of the kivu checkbox provider snap
# To run : snap run checkbox-kivu-classic.<app>
#
# checkbox-cli:
#   - checkbox client, can be used to talk to the checkbox daemon
# configure:
#   - inject environment variable into checkbox snap environnement
#     the variable initial list can be found in config/config_vars
#     use configure -l to get the list of the current variables
#     For example, a useful use case is to inject environment variable
#     to enable debugging output (LIBVA_MESSAGING_LEVEL)
# remote-slave:
#   - checkbox slave daemon that will the responsible for running the test sesssion
#     in the remote fashion (through checkbox-cli)
# shell:
#   - give shell access to the provider snap
# install-full-deps:
#   - install all depedencies needed for provider jobs
# regression-testing:
#   - Run the OpenCL regression test suite
apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
  configure:
    command-chain: [bin/wrapper_local]
    command: bin/configure
  regression-testing:
    command-chain: [bin/wrapper_local]
    command: bin/regression-testing
  remote-slave:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper slave
    daemon: simple
    restart-condition: always
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
  install-full-deps:
    command: bin/install-full-deps

passthrough:
  hooks:
    configure:
      command-chain: [bin/wrapper_local]

parts:
  checkbox-provider-opencl:
    plugin: dump
    source: ./checkbox-provider-opencl
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox22
    stage-packages:
      - python3-tinydb
      - python3-filelock
      - intel-gpu-tools
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.10/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "/snap/checkbox22/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      checkbox-provider-tools validate
      checkbox-provider-tools build
      checkbox-provider-tools install --layout=relocatable --prefix=/providers/checkbox-provider-opencl --root="$SNAPCRAFT_PART_INSTALL"
  bin:
    plugin: dump
    source: bin/
    organize:
      '*': bin/
  config-variables:
    plugin: dump
    source: config/

