name: checkbox-kivu-classic
summary: Checkbox tests for the kivu classic project
description: |
  Collection of tests to be run on devices that are part of the kivu project
version: '1.0'
confinement: classic
grade: stable

base: core22

# Here are the available applications of the kivu checkbox provider snap
# To run : snap run checkbox-kivu-classic.<app>
#
# checkbox-cli:
#   - checkbox client, can be used to talk to the checkbox daemon
# configure:
#   - inject environment variable into checkbox snap environnement
#     the variable initial list can be found in config/config_vars
#     use configure -l to get the list of the current variables
#     For example, a useful use case is to inject environment variable
#     to enable debugging output (LIBVA_MESSAGING_LEVEL)
# remote-slave:
#   - checkbox slave daemon that will the responsible for running the test sesssion
#     in the remote fashion (through checkbox-cli)
# test-runner / test-runner-automated:
#   - execute all provider tests inside the snap environment
#     the test execution is standalone and does not depend on the remote-slave daemon
# shell:
#   - give shell access to the provider snap
# test-runner-automated-hwdec:
#   - execute hardware decoding tests
#     the test execution is standalone and does not depend on the remote-slave daemon
apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
  configure:
    command-chain: [bin/wrapper_local]
    command: bin/configure
  remote-slave:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper slave
    daemon: simple
    restart-condition: always
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
  test-runner:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner
  test-runner-automated:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner-automated
  test-runner-automated-hwdec:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner-automated-hwdec
  run-hwdec-check:
    command: bin/run-hwdec-check

passthrough:
  hooks:
    configure:
      command-chain: [bin/wrapper_local]

parts:
  checkbox-provider-kivu:
    plugin: dump
    source: ./checkbox-provider-kivu
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox22
    stage-packages:
      - python3-tinydb
      - python3-filelock
      - intel-gpu-tools
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.10/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "/snap/checkbox22/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      checkbox-provider-tools validate
      checkbox-provider-tools build
      checkbox-provider-tools install --layout=relocatable --prefix=/providers/checkbox-provider-kivu --root="$SNAPCRAFT_PART_INSTALL"
  launchers:
    plugin: dump
    source: launchers/
    organize:
      '*': bin/
  config-variables:
    plugin: dump
    source: config/

